"""add phone number

Revision ID: 5f04d29aea98
Revises: ae514c7f6689
Create Date: 2025-07-18 16:25:42.055814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f04d29aea98'
down_revision: Union[str, Sequence[str], None] = 'ae514c7f6689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('y_users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('y_users', 'phone_number')
    # ### end Alembic commands ###
